apiVersion: v1
kind: Template
metadata:
  name: selectorsyncset-template

parameters:
  - name: REGISTRY_IMG
    required: true
  - name: PACKAGE_IMG
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE_DIGEST
    required: true
  - name: REPO_NAME
    value: package-operator
    required: true
  - name: DISPLAY_NAME
    value: Package Operator
    required: true

objects:
  - apiVersion: hive.openshift.io/v1
    kind: SelectorSyncSet
    metadata:
      annotations:
        component-display-name: ${DISPLAY_NAME}
        component-name: ${REPO_NAME}
      labels:
        managed.openshift.io/osd: "true"
      name: package-operator
    spec:
      clusterDeploymentSelector:
        matchLabels:
          ext-hypershift.openshift.io/cluster-type: management-cluster
      resourceApplyMode: Sync
      resources:
        - apiVersion: v1
          kind: Namespace
          metadata:
            name: openshift-package-operator
            labels:
              openshift.io/cluster-monitoring: "true"
